# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 11d5393be39aa45a86bff96cecea394c2fa19ab8503e4170977b4f54e5669af2f1dce03be2382ec4c21bac0a8909c0d8f45834787b305d9f7ae7676721c171f7

test:
  secret_key_base: 2467026d7cfe6a2dc00100041d566ef9532ab4c91fe67cae30f4d0251045476fc23e9de36c4787206661f5a3dc5620292d4547fd1a38251f9bcfbf429eb3ae45

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
